classdef IndividualCMFIntegrationTest < matlab.unittest.TestCase
    
    properties
        Data
        Wavelengths
        Tolerance = 1e-10; % Floating point tolerance
    end
    
    methods(TestMethodSetup)
        function loadData(testCase)
            % Load the CSV generated by the Python script
            % Assumes 'tests/data/individual_verification.csv' contains columns for:
            % - Shifted Individual (L_energy, M_energy, etc.)
            % - Lens Aging (lens_dens_60, etc.)
            % - Field Size (mac_dens_4deg, etc.)
            try
                testCase.Data = readtable('tests/data/individual_verification.csv'); 
                testCase.Wavelengths = testCase.Data.nm;
            catch
                % Fallback if running from root
                testCase.Data = readtable('individual_verification.csv');
                testCase.Wavelengths = testCase.Data.nm;
            end
        end
    end
    
    methods(Test)
        
        %% --- Discrepancy Fixes (Shifted Individual) ---
        
        function testShiftedIndividualEnergy(testCase)
            % Verify the full energy calculation for a "Shifted" individual.
            %
            % Python Parameters:
            %   L_Shift = 5.0, M_Shift = -5.0
            %   Lod/Mod = 0.60, Sod = 0.45
            %   Macular = 0.50, Lens = 2.00
            %   Template = "Serine"

            % Use explicit Sampled normalization with matching CSV resolution.
            % The CSV data is at 5nm resolution, so we configure the normalization
            % to use the same wavelength grid for peak finding.
            obs = IndividualCMF(...
                'L_OpsinTemplate', "Serine", ...
                'L_LambdaMaxShift', 5.0, ...
                'M_LambdaMaxShift', -5.0, ...
                'Lod', 0.60, ...
                'Mod', 0.60, ...
                'Sod', 0.45, ...
                'MacularDensity', 0.50, ...
                'LensDensity', 2.00, ...
                'OutputFormat', "energy", ...
                'NormalizeOutput', true, ...
                'NormalizationMethod', struct('Method', "Sampled", ...
                    'Start', 380, 'Stop', 780, 'Step', 5));  % Match CSV grid

            % 1. Compare L-Cone Energy - normalization now handled by the class
            L_energy_matlab = obs.L(testCase.Wavelengths);

            testCase.verifyEqual(L_energy_matlab, testCase.Data.L_energy, ...
                'AbsTol', testCase.Tolerance, ...
                'L-Cone Energy (Shifted +5nm) should match Python shape');

            % 2. Compare M-Cone Energy
            M_energy_matlab = obs.M(testCase.Wavelengths);

            testCase.verifyEqual(M_energy_matlab, testCase.Data.M_energy, ...
                'AbsTol', testCase.Tolerance, ...
                'M-Cone Energy (Shifted -5nm) should match Python shape');

            % 3. Compare S-Cone Energy
            S_energy_matlab = obs.S(testCase.Wavelengths);

            testCase.verifyEqual(S_energy_matlab, testCase.Data.S_energy, ...
                'AbsTol', testCase.Tolerance, ...
                'S-Cone Energy should match Python shape');
        end

        function testShiftedIndividualQuantal(testCase)
            % Verify Quantal output format matches Python intermediate data

            % Use explicit Sampled normalization with matching CSV resolution.
            obs = IndividualCMF(...
                'L_OpsinTemplate', "Serine", ...
                'L_LambdaMaxShift', 5.0, ...
                'M_LambdaMaxShift', -5.0, ...
                'Lod', 0.60, ...
                'Mod', 0.60, ...
                'Sod', 0.45, ...
                'MacularDensity', 0.50, ...
                'LensDensity', 2.00, ...
                'OutputFormat', "quantal", ...
                'NormalizeOutput', true, ...
                'NormalizationMethod', struct('Method', "Sampled", ...
                    'Start', 380, 'Stop', 780, 'Step', 5));  % Match CSV grid

            L_quantal_matlab = obs.L(testCase.Wavelengths);

            testCase.verifyEqual(L_quantal_matlab, testCase.Data.L_quantal, ...
                'AbsTol', testCase.Tolerance, ...
                'L-Cone Quantal Sensitivity should match Python shape');
        end
        
        %% --- Physiology Tests (Lens, Macular, Field Size) ---
        
        function testLensAging(testCase)
            % Validate Lens Density logic for Age 60 and 80
            % Checks against python calculated peaks (approx 400nm)
            
            idx_400 = find(testCase.Wavelengths == 400);
            if isempty(idx_400), idx_400 = 3; end % Fallback for standard grid
            
            % Case 1: Age 32 (Standard)
            obs32 = IndividualCMF(Age=32, FieldSize=10);
            testCase.verifyEqual(obs32.LensDensity, 1.7649, 'AbsTol', 1e-4);
            
            % Case 2: Age 60
            % Check that the MATLAB class calculates the same density scalar 
            % as the Python script generated in the 'lens_dens_60' curve.
            if ismember('lens_dens_60', testCase.Data.Properties.VariableNames)
                obs60 = IndividualCMF(Age=60, FieldSize=10);
                expected_60_at_400 = testCase.Data.lens_dens_60(idx_400);
                testCase.verifyEqual(obs60.LensDensity, expected_60_at_400, 'AbsTol', 1e-3, ...
                    'Age 60 Lens Density property should match Python calculated peak');
            end
            
            % Case 3: Age 80
            if ismember('lens_dens_80', testCase.Data.Properties.VariableNames)
                obs80 = IndividualCMF(Age=80, FieldSize=10);
                expected_80_at_400 = testCase.Data.lens_dens_80(idx_400);
                testCase.verifyEqual(obs80.LensDensity, expected_80_at_400, 'AbsTol', 1e-3, ...
                    'Age 80 Lens Density property should match Python calculated peak');
            end
        end
        
        function testFieldSizeScaling(testCase)
            % Validate Macular and Photopigment scaling for FieldSize = 4
            
            obs4 = IndividualCMF(Age=32, FieldSize=4);
            
            % 1. Check Macular Density Peak (Formula: D = 0.485 * exp(-4.0 / 6.132))
            expected_mac_peak = 0.485 * exp(-4.0 / 6.132);
            testCase.verifyEqual(obs4.MacularDensity, expected_mac_peak, 'AbsTol', 1e-4, ...
                'Field Size 4 should result in correct Macular Density property');
            
            % 2. Check Photopigment Densities (Lod, Mod, Sod)
            % L/M: D = 0.38 + 0.54 * exp(-4.0 / 1.333)
            expected_lod = 0.38 + 0.54 * exp(-4.0 / 1.333);
            % S: D = 0.30 + 0.45 * exp(-4.0 / 1.333)
            expected_sod = 0.30 + 0.45 * exp(-4.0 / 1.333);
            
            testCase.verifyEqual(obs4.Lod, expected_lod, 'AbsTol', 1e-4);
            testCase.verifyEqual(obs4.Mod, expected_lod, 'AbsTol', 1e-4);
            testCase.verifyEqual(obs4.Sod, expected_sod, 'AbsTol', 1e-4);
        end
        
        function testComplexIndividualPipeline(testCase)
            % Verify a complex individual (Age 60, Field 4) against raw energy data
            % Only run if complex data columns exist
            
            if ismember('complex_L_energy', testCase.Data.Properties.VariableNames)
                obsComplex = IndividualCMF(Age=60, FieldSize=4, ...
                    NormalizeOutput=false, ... 
                    OutputFormat="energy");
                    
                L_energy_matlab = obsComplex.L(testCase.Wavelengths);
                M_energy_matlab = obsComplex.M(testCase.Wavelengths);
                
                testCase.verifyEqual(L_energy_matlab, testCase.Data.complex_L_energy, 'RelTol', 1e-3, ...
                    'Complex Individual (Age 60, Field 4) L-Energy must match Python');
                    
                testCase.verifyEqual(M_energy_matlab, testCase.Data.complex_M_energy, 'RelTol', 1e-3, ...
                    'Complex Individual (Age 60, Field 4) M-Energy must match Python');
            end
        end

        %% --- Logic & Behavior Tests ---
        
        function testManualOverrideBehavior(testCase)
            % Verify that setting properties manually overrides defaults
            % and retains the values.
            
            obs = IndividualCMF();
            
            % Set manual densities
            obs.LensDensity = 1.23;
            obs.MacularDensity = 0.45;
            obs.Lod = 0.67;
            
            testCase.verifyEqual(obs.LensDensity, 1.23, 'LensDensity set failed');
            testCase.verifyEqual(obs.MacularDensity, 0.45, 'MacularDensity set failed');
            testCase.verifyEqual(obs.Lod, 0.67, 'Lod set failed');
            
            % Verify internal algorithm flags switched to "Custom"
            testCase.verifyEqual(string(obs.MacularDensityAlgorithm), "Custom", ...
                'Setting MacularDensity should switch Algorithm to Custom');
            testCase.verifyEqual(string(obs.PhotopigmentDensityAlgorithm), "Custom", ...
                'Setting Lod should switch Algorithm to Custom');
        end
        
        function testIndividualCMFWithAllParameters(testCase)
            % Test creating observer with many parameters
            obs = IndividualCMF(...
                Age=45, ...
                FieldSize=4, ...
                Lod=0.4, ...
                Mod=0.35, ...
                Sod=0.3, ...
                MacularDensity=0.3, ...
                LensDensity=1.5, ...
                L_OpsinTemplate="Serine", ...
                L_LambdaMaxShift=2, ...
                M_LambdaMaxShift=-2, ...
                S_LambdaMaxShift=1);

            wl = (400:10:700)';
            l = obs.L(wl);
            m = obs.M(wl);
            s = obs.S(wl);

            testCase.verifySize(l, [numel(wl), 1]);
            testCase.verifySize(m, [numel(wl), 1]);
            testCase.verifySize(s, [numel(wl), 1]);
        end

        function testFieldSizeIndependence(testCase)
            % Verify that changing FieldSize does NOT overwrite manual densities
            % if the Algorithm is "Custom".
            
            obs = IndividualCMF();
            
            % 1. Set Custom Densities
            obs.MacularDensity = 0.8;
            obs.MacularDensityAlgorithm = "Custom"; % Explicitly lock it
            
            % 2. Change Field Size (which usually triggers recalc)
            obs.FieldSize = 2; 
            
            % 3. Verify Density remains 0.8 (Standard 2deg is 0.35)
            testCase.verifyEqual(obs.MacularDensity, 0.8, ...
                'FieldSize change should not overwrite Custom MacularDensity');
                
            % 4. Verify Behavior without Custom lock
            % If we reset to Standard, it should change.
            % Suppress expected MacularCustomOverwritten warning for the
            % switch back to CIE Constants (fixture restores cleanly).
            testCase.applyFixture( ...
                matlab.unittest.fixtures.SuppressedWarningsFixture( ...
                    'IndividualCMF:MacularCustomOverwritten'));
            obs.MacularDensityAlgorithm = "CIE170";
            obs.FieldSize = 2; 
            testCase.verifyEqual(obs.MacularDensity, 0.35, ...
                'FieldSize change SHOULD overwrite when Algorithm is CIE Constants');
        end
    end
end