classdef PreReceptoralStageTest < matlab.unittest.TestCase
    % PRERECEPTORALSTAGETEST  Characterization tests for pipeline.PreReceptoralStage.
    %
    %   Pins the pure-function behavior of the stage so the extraction
    %   from IndividualCMF is verifiable in isolation. Equivalence with
    %   the previous IndividualCMF behavior is covered by the existing
    %   public-API test suite (IndividualCMFLensModelTest, EvaluateTest,
    %   etc.) which all flow through the pipeline.

    % SPDX-License-Identifier: AGPL-3.0-or-later
    %
    % Copyright (c) 2025-2026 Alexander Forsythe and Brian Funt
    % Simon Fraser University, Burnaby, British Columbia, Canada

    methods (Test)
        function testApplyFiltersPreservesShape(testCase)
            % Output must be the same shape as the input absorptance.
            wl = (400:5:700)';
            absorptance = ones(size(wl)) * 0.5;
            quantal = pipeline.PreReceptoralStage.applyFilters( ...
                absorptance, wl, ...
                LensTemplate=StockmanRiderLensTemplate(), ...
                LensDensity=CIE170.STD_LENS_DENSITY_400, ...
                MacularTemplate=StockmanRider2023MacularTemplate(), ...
                MacularDensity=CIE170.STD_10DEG_MACULAR_DENSITY, ...
                Age=CIE170.STD_AGE);
            testCase.verifySize(quantal, size(wl));
        end

        function testApplyFiltersIsAttenuating(testCase)
            % Pre-receptoral filters can only attenuate, never amplify.
            wl = (400:5:700)';
            absorptance = ones(size(wl)) * 0.5;
            quantal = pipeline.PreReceptoralStage.applyFilters( ...
                absorptance, wl, ...
                LensTemplate=StockmanRiderLensTemplate(), ...
                LensDensity=CIE170.STD_LENS_DENSITY_400, ...
                MacularTemplate=StockmanRider2023MacularTemplate(), ...
                MacularDensity=CIE170.STD_10DEG_MACULAR_DENSITY, ...
                Age=CIE170.STD_AGE);
            testCase.verifyLessThanOrEqual(quantal, absorptance);
        end

        function testZeroDensitiesPassThrough(testCase)
            % With zero density on both filters, transmission == 1 and the
            % output equals the input absorptance.
            wl = (400:5:700)';
            absorptance = sin((1:numel(wl))' / 10);  % arbitrary non-trivial input
            quantal = pipeline.PreReceptoralStage.applyFilters( ...
                absorptance, wl, ...
                LensTemplate=StockmanRiderLensTemplate(), ...
                LensDensity=0, ...
                MacularTemplate=StockmanRider2023MacularTemplate(), ...
                MacularDensity=0, ...
                Age=CIE170.STD_AGE);
            testCase.verifyEqual(quantal, absorptance, 'AbsTol', 1e-12);
        end

        function testHigherLensDensityAttenuatesMore(testCase)
            % Increasing lens density must monotonically reduce quantal
            % output everywhere the lens template is non-zero. Verifies
            % math direction without coupling to a specific cone.
            wl = (400:5:700)';
            absorptance = ones(size(wl));
            lens = StockmanRiderLensTemplate();
            macular = StockmanRider2023MacularTemplate();
            lowLens = pipeline.PreReceptoralStage.applyFilters( ...
                absorptance, wl, ...
                LensTemplate=lens, LensDensity=0.5, ...
                MacularTemplate=macular, MacularDensity=CIE170.STD_10DEG_MACULAR_DENSITY, ...
                Age=CIE170.STD_AGE);
            highLens = pipeline.PreReceptoralStage.applyFilters( ...
                absorptance, wl, ...
                LensTemplate=lens, LensDensity=2.0, ...
                MacularTemplate=macular, MacularDensity=CIE170.STD_10DEG_MACULAR_DENSITY, ...
                Age=CIE170.STD_AGE);
            testCase.verifyLessThanOrEqual(highLens, lowLens);
        end

        function testAgeAffectsAgingLensTemplate(testCase)
            % For an age-dependent lens template (Pokorny 1987), a larger
            % age must produce more attenuation at short wavelengths
            % (lens yellowing). Tests that the age argument is wired
            % through correctly.
            wl = (400:5:500)';  % short-wavelength region where aging shows
            absorptance = ones(size(wl));
            lens = Pokorny1987LensTemplate();
            macular = StockmanRider2023MacularTemplate();
            youngQuantal = pipeline.PreReceptoralStage.applyFilters( ...
                absorptance, wl, ...
                LensTemplate=lens, LensDensity=1.0, ...
                MacularTemplate=macular, MacularDensity=CIE170.STD_10DEG_MACULAR_DENSITY, ...
                Age=25);
            oldQuantal = pipeline.PreReceptoralStage.applyFilters( ...
                absorptance, wl, ...
                LensTemplate=lens, LensDensity=1.0, ...
                MacularTemplate=macular, MacularDensity=CIE170.STD_10DEG_MACULAR_DENSITY, ...
                Age=75);
            % Older lens absorbs more, so quantal output is lower.
            testCase.verifyLessThanOrEqual(oldQuantal, youngQuantal);
        end
    end
end
